config/routes.rb
SavantTime::Application.routes.draw do

  resources :notifications, only: [] do
    collection do
      match "callback", via: [:get, :post]
    end
  end
  resources :inventory_jobs, only: [:create]
  resources :archive_retrieval_jobs, only: [:create]
  resources :archive_jobs, only: [] do
    collection do
      post "bulk_create"
    end
  end
  resources :archives, only: [:index, :destroy]

  get '/entries/(*path)' => 'directory_entries#index', as: :entries, format: false
  post '/entries/(*path)' => 'archive_jobs#create', format: false

  root to: redirect("/entries/")

end

app/models/archive.rb
class Archive < ActiveRecord::Base
  validates :aid, presence: true, uniqueness: true
  belongs_to :archive_job, foreign_key: :aid, primary_key: :jid, dependent: :destroy

  after_destroy :destroy_remote

  paginates_per 200

  # SQLiteでは8bit INTしか扱えず文字列として保持しているので、整数に変換してから返す
  def filesize
    super.to_i
  end

  def retrieve
    glacier = Glacier.new
    glacier.retrieve_archive(aid)
  end

  def verify
    return unless File.exists?(archive_job.fullpath)
    sha256 == Treehash.calculate_tree_hash(File.open(archive_job.fullpath))
  end

  private
  def destroy_remote
    glacier = Glacier.new
    glacier.destroy_archive(aid)
  end
end

app/models/archive_job.rb
class ArchiveJob < ActiveRecord::Base
  has_one :archive, foreign_key: :aid, primary_key: :jid

  paginates_per 200
end

app/models/archive_retrieval_job.rb
class ArchiveRetrievalJob < ActiveRecord::Base
  validates :jid, presence: true

  def job
    return @job if @job

    glacier = Glacier.new(nil)
    @job = glacier.vault.jobs.get(jid)
  end

  def write_output(aid)
    archive = Archive.find_by!(aid: aid)
    File.open(Pathname(Settings.download_dir) + archive.description, "wb:ASCII-8BIT") do |f|
      job.get_output io: f
    end
  end
end

app/models/directory_entry.rb
class DirectoryEntry
  include ActiveModel::Model
  attr_accessor :name, :fullpath, :pathname, :size, :archive_jobs

  def initialize(path)
    raise "#{path} is not directory" unless File.directory?(path)

    @name = File.basename(path)
    @fullpath = path
    @pathname = Pathname.new(path)
    @dir = Dir.open(path)
  end

  def entries(page, per_page = 500)
    return Kaminari.paginate_array(@entries).page(page).per(per_page) if @entries

    dirs = []
    files = []
    Dir.glob((pathname + "*").to_s).map do |e|
      if File.directory?(e)
        dirs << DirectoryEntry.new(e)
      else
        files << FileEntry.new(e)
      end
    end

    dirs.sort_by!(&:name)
    files.sort_by!(&:name)

    @entries = dirs.concat(files)
    Kaminari.paginate_array(@entries).page(page).per(per_page)
  end
end

app/models/file_entry.rb
class FileEntry
  include ActiveModel::Model
  attr_accessor :name, :fullpath, :pathname, :size, :archive_job

  def initialize(path)
    raise "#{path} is not exist" unless File.exists?(path)
    @name = File.basename(path)
    @fullpath = path
    @pathname = Pathname.new(path)
    @size = FileTest.size(path)
  end

  def archive_job_from_collection(collection)
    collection[fullpath]
  end
end

app/models/glacier.rb
class Glacier
  def initialize(path = nil)
    @path = path
  end

  def archive_create
    return nil if ArchiveJob.exists?(fullpath: @path)

    archive = vault.archives.create body: File.open(@path), description: File.basename(@path), :multipart_chunk_size => (1024*1024) * Settings.upload_chunk_size
    ArchiveJob.create!(jid: archive.id, description: File.basename(@path), fullpath: @path)
  end

  def retrieve_inventory
    job = vault.jobs.create(type: Fog::AWS::Glacier::Job::INVENTORY)
    InventoryRetrievalJob.create!(jid: job.id)
  end

  def retrieve_archive(aid)
    job = vault.jobs.create(type: Fog::AWS::Glacier::Job::ARCHIVE, archive_id: aid)
    ArchiveRetrievalJob.create(jid: job.id)
  end

  def destroy_archive(aid)
    vault.archives.get(aid).destroy
  end

  def glacier
    @glacier ||= Fog::AWS::Glacier.new(aws_access_key_id: Settings.aws_access_key_id, aws_secret_access_key: Settings.aws_secret_access_key, region: Settings.aws_region)
  end

  def vault
    @vault ||= glacier.vaults.create id: Settings.vault_name
  end
end

app/models/inventory_retrieval_job.rb
class InventoryRetrievalJob < ActiveRecord::Base
  validates :jid, presence: true

  def job
    return @job if @job

    glacier = Glacier.new(nil)
    @job = glacier.vault.jobs.get(jid)
  end

  def archive_list
    job.get_output.body["ArchiveList"].map do |attrs|
      Archive.new(aid: attrs["ArchiveId"], description: URI.unescape(attrs["ArchiveDescription"]), filesize: attrs["Size"].to_s, sha256: attrs["SHA256TreeHash"])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def current_path
    params[:path] || ""
  end
  helper_method :current_path

  private
  def digest_authenticate
    authenticate_or_request_with_http_digest do |username|
      if username == Settings.login_user
        Settings.login_password
      else
        false
      end
    end
  end
end

app/controllers/archive_jobs_controller.rb
class ArchiveJobsController < ApplicationController
  before_action :digest_authenticate

  def create
    root_path = Pathname.new(Settings.root_dir)
    real_path = root_path + "#{current_path}"
    ArchiveWorker.perform_async(real_path.to_s)
    render nothing: true, status: :ok
  end

  def bulk_create
    params[:targets].map {|t| URI.unescape(t)}.each do |fullpath|
      ArchiveWorker.perform_async(fullpath)
    end
    render nothing: true, status: :ok
  end
end

app/controllers/archive_retrieval_jobs_controller.rb
class ArchiveRetrievalJobsController < ApplicationController
  before_action :digest_authenticate

  def create
    archive = Archive.find(params[:archive_id])
    archive.retrieve
    render nothing: true, status: :ok
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :digest_authenticate

  def index
    @archives = Archive.joins(:archive_job).includes(:archive_job).order("archive_jobs.fullpath ASC").page(params[:page])
  end

  def destroy
    @archive = Archive.find(params[:id])
    @archive.destroy
    render nothing: true, status: :ok
  end
end

app/controllers/directory_entries_controller.rb
class DirectoryEntriesController < ApplicationController
  before_action :digest_authenticate

  def index
    root_path = Pathname.new(Settings.root_dir)
    real_path = root_path + current_path
    @directory = DirectoryEntry.new(real_path.to_s)
    @entries = @directory.entries(params[:page])
    @archive_jobs = ArchiveJob.where(fullpath: @entries.map(&:fullpath))
    @loaded_archive_jobs = @archive_jobs.group_by {|j| j.fullpath}
    @archives = Archive.where(aid: @archive_jobs.pluck(:jid))
    @loaded_archives = @archives.group_by {|a| a.aid}
  end
end

app/controllers/inventory_jobs_controller.rb
class InventoryJobsController < ApplicationController
  before_action :digest_authenticate

  def create
    glacier = Glacier.new(nil)
    glacier.retrieve_inventory
    render nothing: true, status: :ok
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  protect_from_forgery except: [:callback]

  def callback
    json = ActiveSupport::JSON.decode(request.body.read)
    Rails.logger.info json.inspect
    Rails.logger.error "Message Not Found" unless json["Message"]

    message = ActiveSupport::JSON.decode(json["Message"])
    process_notification_message(message)
    render nothing: true, status: :ok
  end

  private
  def process_notification_message(message)
    Rails.logger.error message["StatusMessage"] unless message["StatusCode"] == "Succeeded"
    case message["Action"]
    when "InventoryRetrieval"
      jid = message["JobId"]
      inventory_retrieval_job = InventoryRetrievalJob.find_by!(jid: jid)
      inventory_retrieval_job.archive_list.each(&:save)
    when "ArchiveRetrieval"
      jid = message["JobId"]
      aid = message["ArchiveId"]
      ArchiveDownloadWorker.perform_async(jid, aid)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parent_path(path)
    parent = Pathname(path).parent
    if parent.to_s == "."
      entries_path
    else
      entries_path(URI.escape("#{parent.to_s}"))
    end
  end

  def child_path(path)
    if current_path.present?
      entries_path(URI.escape("#{current_path}/#{path}"))
    else
      entries_path(URI.escape("#{path}"))
    end
  end
end

app/helpers/archive_jobs_helper.rb
module ArchiveJobsHelper
end

app/helpers/directory_entries_helper.rb
module DirectoryEntriesHelper
end

app/views/archives/_archive.html.haml
%tr
  %td.target-check
  %td.entry_name= archive_job.try(:fullpath) || archive.description
  %td.size= archive.try(:filesize) || "インベントリ取得待ち"
  %td.action= archive.try(:retrieve_link) || "インベントリ取得待ち"
  %td.destroy-action= archive.try(:destroy_link) || "インベントリ取得待ち"

app/views/archives/index.html.haml
= paginate @archives
%table.table
  %thead
    %tr
      %th.target-check
      %th.entry_name
        fullpath
      %th.size
        filesize
      %th.action
      %th.destroy-action
  %tbody
    - @archives.each do |archive|
      = render "archive", archive_job: archive.archive_job, archive: archive
= paginate @archives

app/views/directory_entries/_archive_jobed_entry.html.haml
%tr
  %td.target-check
  %td.entry_name= entry.entry_name
  %td.size= entry.size
  %td.action バックアップジョブ済

app/views/directory_entries/_archived_entry.html.haml
%tr
  %td.target-check
  %td.entry_name= entry.entry_name
  %td.size= entry.size
  %td.action アーカイブ済み #{entry.size.to_i == archive.filesize.to_i ? "(サイズ一致)" : "(サイズ不一致)"} &nbsp; #{archive.retrieve_link}

app/views/directory_entries/_backuped_entry.html.haml
%tr
  %td.target-check
  %td.entry_name= entry.entry_name
  %td.size= entry.size
  %td.action バックアップジョブ済

app/views/directory_entries/_entry.html.haml
%tr
  %td.target-check= entry.check_box
  %td.entry_name= entry.entry_name
  %td.size= entry.size
  %td.action= entry.action

app/views/directory_entries/index.html.haml
= paginate @entries

#check-menu
  = button_tag "All Check", class: %w(btn btn-default js-all-check)
  = button_tag "Clear", type: "reset", class: %w(btn btn-default js-all-uncheck)
  = link_to "Get Inventory", inventory_jobs_path, remote: true, method: :post, class: %w(btn btn-default js-retrieve-inventory)

= form_tag bulk_create_archive_jobs_path, remote: true, id: "bulk-archive-form" do
  = submit_tag("Bulk Archive", class: %w(btn btn-primary))
  %table.table
    %thead
      %tr
        %th.target-check
        %th.entry_name
          name
        %th.size
          filesize
        %th.action
    %tbody
      - if current_path.present?
        %tr
          %td.target-check
          %td.entry_name= link_to "..", parent_path(current_path)
          %td.size
          %td.action

      - @entries.each do |entry|
        - if archive_job = @loaded_archive_jobs[entry.fullpath]
          - if archive = @loaded_archives[archive_job.first.jid]
            = render "archived_entry", entry: entry, archive: archive.first
          - else
            = render "archive_jobed_entry", entry: entry
        - else
          = render "entry", entry: entry
= paginate @entries

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Savant Time
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse{role: "navigation"}
      .navbar-header
        = link_to "Savant Time", root_path, class: "navbar-brand"
      .navvar-collapse.navbar-inverse-collapse
        %ul.nav.navbar-nav
          %li
            = link_to "Home", entries_path
          %li
            = link_to "Archives", archives_path

    #main.container-fluid
      = yield